'------------------------------------------------------------------------------
' <auto-generated>
'     此代码由工具生成。
'     运行时版本:4.0.30319.42000
'
'     对此文件的更改可能会导致不正确的行为，并且如果
'     重新生成代码，这些更改将会丢失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    '此类是由 StronglyTypedResourceBuilder
    '类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    '若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    '(以 /str 作为命令选项)，或重新生成 VS 项目。
    '''<summary>
    '''  一个强类型的资源类，用于查找本地化的字符串等。
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class IconResource
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  返回此类使用的缓存的 ResourceManager 实例。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("SwiftConnector.IconResource", GetType(IconResource).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  重写当前线程的 CurrentUICulture 属性，对
        '''  使用此强类型资源类的所有资源查找执行重写。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property de() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("de", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property en() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("en", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property es() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("es", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property fr() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fr", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property ja() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ja", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property ko() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ko", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property mysql_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mysql_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property mysql_64() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mysql_64", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property mysql_large_64() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mysql_large_64", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property mysql_mini_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mysql_mini_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property oracle_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("oracle_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property oracle_64() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("oracle_64", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property oracle_large_64() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("oracle_large_64", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property oracle_mini_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("oracle_mini_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property postgresql_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("postgresql_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property postgresql_64() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("postgresql_64", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property postgresql_large_64() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("postgresql_large_64", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property postgresql_mini_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("postgresql_mini_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property pt() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pt", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property ru() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ru", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property sqlite_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sqlite_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property sqlite_64() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sqlite_64", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property sqlite_large_64() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sqlite_large_64", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property sqlite_mini_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sqlite_mini_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property sqlserver_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sqlserver_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property sqlserver_64() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sqlserver_64", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property sqlserver_large_64() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sqlserver_large_64", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property sqlserver_mini_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sqlserver_mini_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property zh() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("zh", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Class
End Namespace
